---
title: "Evelia Coss-Navarrete's CV"
author: Evelia Coss
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Template https://docs.google.com/spreadsheets/d/1lwyoVE3-IVUFhudN6B5EqXJ9wMBbze9gmrJJ8rT2trs/edit?gid=917338460#gid=917338460

# Ultima actualizacion https://github.com/nstrayer/cv/blob/master/cv.Rmd

# Read in all data and initialize a CV printer object
#CV <- create_CV_object(
#  data_location = "https://docs.google.com/spreadsheets/d/1JckGt60BNWheMo23d6bloYLq27h2t5X7hGAXsj0Mlwo/edit?usp=sharing",  
#  pdf_mode = params$pdf_mode
#)

CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1lwyoVE3-IVUFhudN6B5EqXJ9wMBbze9gmrJJ8rT2trs/edit?gid=917338460#gid=917338460",  
  pdf_mode = params$pdf_mode
 )

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
#datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
#if(params$pdf_mode){
#  cat("View this CV online with links at _mpadilla905.github.io/cv/_")
#} else {
#  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/mpadilla905/mpadilla905.github.io/cv/mpadilla_cv.pdf)")
#}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```

<br>
<br>

Programming Languages {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_programming_languages()
```

<br>

Languages {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_languages()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available at [EveliaCoss/CV](https://github.com/EveliaCoss/CV) and is powered by [nstrayer/cv](https://github.com/nstrayer/cv).

Last updated on `r Sys.Date()`.



Main
================================================================================

Emiliano Ferro Rodriguez {#title}
------------------------------------------------------------------------------

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



```{r}
CV %<>% print_links()
```

